# Generated by Django 3.2.3 on 2021-06-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('tasks', '0002_alter_mytasks_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytasks',
            name='user_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
